# Constants for the application

# List of available languages in the dataset
LANGUAGES = [
    "all",  # Special value to indicate all languages
    "brazilian",
    "bulgarian",
    "czech",
    "danish",
    "dutch",
    "english",
    "finnish",
    "french",
    "german",
    "greek",
    "hungarian",
    "indonesian",
    "italian",
    "japanese",
    "koreana",
    "latam",
    "norwegian",
    "polish",
    "portuguese",
    "romanian",
    "russian",
    "schinese",
    "spanish",
    "swedish",
    "tchinese",
    "thai",
    "turkish",
    "ukrainian",
    "vietnamese"
]

# Language display names (for UI)
LANGUAGE_DISPLAY_NAMES = {
    "all": "All Languages",
    "brazilian": "Brazilian Portuguese",
    "bulgarian": "Bulgarian",
    "czech": "Czech",
    "danish": "Danish",
    "dutch": "Dutch",
    "english": "English",
    "finnish": "Finnish",
    "french": "French",
    "german": "German",
    "greek": "Greek",
    "hungarian": "Hungarian",
    "indonesian": "Indonesian",
    "italian": "Italian",
    "japanese": "Japanese",
    "koreana": "Korean",
    "latam": "Latin American Spanish",
    "norwegian": "Norwegian",
    "polish": "Polish",
    "portuguese": "Portuguese",
    "romanian": "Romanian",
    "russian": "Russian",
    "schinese": "Simplified Chinese",
    "spanish": "Spanish",
    "swedish": "Swedish",
    "tchinese": "Traditional Chinese",
    "thai": "Thai",
    "turkish": "Turkish",
    "ukrainian": "Ukrainian",
    "vietnamese": "Vietnamese"
} 