[server]
enableCORS = false
enableXsrfProtection = false

[runner]
fastReruns = true

[client]
toolbarMode = "minimal"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 